### ISSUE TITLE
Can't set description of field with legacy comments

### ISSUE THREAD

**Issue by olivernybroe** [digiaonline/graphql-php#229]
### What did you do?

Created a schema with following strin
```
type Query {
    # Name of the app.
    appName: String
}
```

### What did you expect to happen?
That appName has the description

### What actually happened?
No description

### What version of this project are you using?
dev-master 383d875)

**Comment by crisu83** [comment]
I suspect that the issue is caused by the lack of line-breaks. Can you try the following schema?

```
type Query { 
  # Name of the app. 
  appName: String 
}
```

**Comment by olivernybroe** [comment]
@crisu83 mb. there is line break, just forgot 3 `.

**Comment by crisu83** [comment]
We can consider adding support for legacy comments later if necessary.

**Comment by crisu83** [comment]
We won't be adding legacy any support at least at this time.
