### ISSUE TITLE
[Feat] Support for custom exception handler

### ISSUE THREAD

**Issue by olivernybroe** [digiaonline/graphql-php#231]
### What did you do?
Throw an exception in my resolver.

### What did you expect to happen?
My custom exception handler should be able to resolve the exception to a error.

### What actually happened?
The getMessage method on my exception was thrown as an error instead.

### What version of this project are you using?
`"digiaonline/graphql": "@dev"`

So what I basically mean is that we should be able to register a exception handler in the dependency injection system, to overwrite the default way a exception is handled.

**Comment by Jalle19** [comment]
Related to https://github.com/digiaonline/graphql-php/issues/8

**Comment by crisu83** [comment]
@olivernybroe Do you have any insight on how this should be implemented?
