### ISSUE TITLE
Fix ambiguity with null variable values and default values

### ISSUE THREAD

**Issue by crisu83** [digiaonline/graphql-php#239]
We need to ensure that null variable values and default values are handled correctly. The reference implementation can be found here: https://github.com/graphql/graphql-js/pull/1274/files

**Comment by crisu83** [comment]
@Jalle19 do you know if this issue is done?

**Comment by Jalle19** [comment]
I don't know, but I think the issue still exists

**Comment by crisu83** [comment]
@Jalle19 I think this works as it should in our implementation. I vote for closing this issue and re-opening it if it resurfaces. What do you think?

**Comment by Jalle19** [comment]
Sure
