### ISSUE TITLE
Fix some issues with the ID type

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/graphql-php#255]
See discussion in https://github.com/digiaonline/graphql-php/pull/252#issuecomment-403014120

**Comment by Jalle19** [comment]
No one said we should remove it?

**Comment by crisu83** [comment]
@Jalle19 My bad, I misunderstood your comment.

**Comment by crisu83** [comment]
@Jalle19 Not sure what you'd like to do with this.

**Comment by hugovk** [comment]
Thanks for the report, however we're going to archive this repo soon as we're no longer maintaining it: https://github.com/digiaonline/graphql-php/issues/359
