### ISSUE TITLE
Name issue with Scalar Introspection

### ISSUE THREAD

**Issue by cgrice** [digiaonline/graphql-php#261]
### What did you do?

We have two scalars named `Date` and `Time` that we use in a few places. We also have a test which introspects our types and makes sure we're documenting them all. Introspection of these types seems to be doing something odd with names, possibly calling the object name (clashing with php's `date()` and `time()`)

### What did you expect to happen?

With the following query:

```
{
  __schema {
    types {
      name
      description
    }
  }
}
```

We would expect the result for Date to be:

```
 [
   "name" => "Date"
   "description" => "A date in YYYY-MM-DD format."
 ]
```

and the result for Time to be:

```
[
  "name" => "Time"
   "description" => "Representation of a time in 24H format (e.h. 19:00)."
]
```

### What actually happened?

We are seeing the following responses for Date:

```
 [
   "name" => null
   "description" => "A date in YYYY-MM-DD format."
 ]
```

and for Time:

```
[
  "name" => "1531475584"
   "description" => "Representation of a time in 24H format (e.h. 19:00)."
]
```

The query for Date also includes the following error:

```
[{"message":"date() expects at most 2 parameters, 4 given","locations":[{"line":4,"column":13}],"path":["__type","name"]}]
```

### What version of this project are you using?

I've created a branch of the project which includes a test which breaks due to this issue:

https://github.com/digiaonline/graphql-php/compare/master...cgrice:bug-with-scalar-introspection

There's a commented out piece of code in the IntrospectionProvider which fixes the test, but I'm not sure this is the best approach! I couldn't find the piece of code which is directly causing the issue.

**Comment by crisu83** [comment]
Thanks for reaching out @cgrice! We will certainly have to take a look at what’s causing this. Any chance you could also provide the code that is defining these types? Thank you in advance.

**Comment by crisu83** [comment]
Feel free to join us on Slack if you wish to be involved in this project. https://digiaopensource-slack.now.sh #graphql-php

**Comment by crisu83** [comment]
Oh I see what’s going on. You cannot name the function that produces your custom scalar types like that, unless you namespace them. 

I also now see that it’s a but misleading to call the scalar type functions e.g. `String()`, I actually think we should suffix them with `Type`.

**Comment by cgrice** [comment]
Not sure what you mean, sorry! The example in the issue doesn't define any functions, just a scalar in the SDL. 

Have just realised you can do this with any stdlib function and the resolver will attempt to call it, by the way. For example, if i call a scalar `Phpinfo` I get:

```
[{"message":"phpinfo() expects at most 1 parameter, 4 given","locations":[{"line":4,"column":13}],"path":["__type","name"]}]
```
