### ISSUE TITLE
Validation rules

### ISSUE THREAD

**Issue by crisu83** [digiaonline/graphql-php#3]
We need to add support for validation using the Visitor pattern.

The following rules have been implemented:
- [x] ExecutableDefinitions
- [x] FieldOnCorrectType
- [x] FragmentsOnCompositeTypes
- [x] KnownArgumentNames
- [x] KnownDirectives
- [x] KnownFragmentNames
- [x] KnownTypeNames
- [x] LoneAnonymousOperation
- [x] NoFragmentCycles
- [x] NoUndefinedVariables
- [x] NoUnusedFragments
- [x] NoUnusedVariables
- [x] OverlappingFieldsCanBeMerged
- [x] PossibleFragmentSpreads
- [x] ProvidedNonNullArguments
- [x] ScalarLeafs
- [x] SingleFieldSubscriptions
- [x] UniqueArgumentNames
- [x] UniqueDirectivesPerLocation
- [x] UniqueFragmentNames
- [x] UniqueInputFieldNames
- [x] UniqueOperationNames
- [x] UniqueVariableNames
- [x] ValuesOfCorrectType
- [x] VariablesAreInputTypes
- [x] VariablesDefaultValueAllowed
- [x] VariablesInAllowedPosition

**Comment by crisu83** [comment]
Added in #45.

**Comment by Jalle19** [comment]
Should we close this?
