### ISSUE TITLE
Bump minimum required PHP version to 7.1

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/graphql-php#32]
* the README says it's >= 7.1
* composer.json says >= 7.0
* code uses `: void` etc. so composer.json is wrong

**Comment by hugovk** [comment]
composer.json says php>=7.1:
https://github.com/digiaonline/graphql-php/blob/0bc003709c4ce84cd8dee4ade325d416e1ece66c/composer.json#L13

Did you misread phpunit>=7.0?
https://github.com/digiaonline/graphql-php/blob/0bc003709c4ce84cd8dee4ade325d416e1ece66c/composer.json#L18

**Comment by Jalle19** [comment]
Yes I did indeed. More bullet points though

* PHPUnit 7.0 depends on PHP 7.1
* Travis CI doesn't even try to build on 7.0

**Comment by crisu83** [comment]
@Jalle19 So we can close this issue?

**Comment by Jalle19** [comment]
Not without changing the minimum verdion to 7.1 in composer.json.

**Comment by Jalle19** [comment]
WTF, nevermind, yes we can close this
