### ISSUE TITLE
[Question] How to get requested fields inside resolver function?

### ISSUE THREAD

**Issue by acelot** [digiaonline/graphql-php#342]
### What did you do?
I want to get only the required fields from the database, based on the requested fields.

### What did you expect to happen?
I want an array of the requested fields to transform them into database columns.

**Comment by Jalle19** [comment]
@crisu83

**Comment by acelot** [comment]
I figured it out myself :) All necessary information is available in `ResolveInfo $info` argument.
```php
$fields = array_reduce(
    $info->getFieldNodes()[0]->getSelectionSet()->getSelections(),
    function (array $carry, SelectionNodeInterface $selectionNode) {
        if ($selectionNode instanceof FieldNode) {
            $carry[] = $selectionNode->getNameValue();
        }
        return $carry;
    },
    []
);

var_export($fields);
```
