### ISSUE TITLE
`extend` doesn't work

### ISSUE THREAD

**Issue by acelot** [digiaonline/graphql-php#343]
### What did you do?
I'm trying to extend existing `Query` type with additional field.

### What did you expect to happen?
I want to see `pong` query field.

### What actually happened?
I see only `ping` field.

### What version of this project are you using?
`v1.1.0`

```php
$schema = GraphQL::buildSchema(
    new Source(
        <<<TXT
        schema {
            query: Query
        }
        
        type Query {
            ping: String!
        }
        
        extend type Query {
            pong: String!
        }
        TXT
    ),
    [
        'Query' => [
            'ping' => function () {
                return 'pong';
            },
            'pong' => function () {
                return 'ping';
            },
        ],
    ]
);
```

![2019-05-14-14:25:04-screenshot-cropeed](https://user-images.githubusercontent.com/1065215/57678767-1a2d0800-7654-11e9-8570-0e7f7abb3911.png)

What I am doing wrong?

**Comment by acelot** [comment]
It seems that extending works only via `GraphQL::extendSchema` helper. Is it right?

**Comment by Jalle19** [comment]
> It seems that extending works only via `GraphQL::extendSchema` helper. Is it right?

I think so, yes.
