### ISSUE TITLE
error with php 8.1

### ISSUE THREAD

**Issue by omidxplimbo** [digiaonline/graphql-php#357]
hi i installed php 8.1 and upgraded laravel version to 8.7
when i run composer install getting this error in utils.php file in vendor (utils.php not class just php file) :

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/omid/Desktop/fanap-upgrade2/rad-api/vendor/digiaonline/graphql/src/Language/utils.php on line 167

**Comment by hugovk** [comment]
Thanks for the report, however we're going to archive this repo soon as we're no longer maintaining it: https://github.com/digiaonline/graphql-php/issues/359
