### ISSUE TITLE
End-to-end tests

### ISSUE THREAD

**Issue by crisu83** [digiaonline/graphql-php#36]
We need to port the Star Wars end-to-end tests from the reference implementation to get a better idea of how combat-ready this library is. https://github.com/graphql/graphql-js/tree/master/src/__tests__

**Comment by Jalle19** [comment]
The link in the issue doesn't work

**Comment by crisu83** [comment]
Yes, it's a bug in GH apparently.

**Comment by crisu83** [comment]
Don't start this, I had to implement a part of this while working on #114.

**Comment by crisu83** [comment]
This has been done in #137, #140 and #141.
