### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by crisu83** [digiaonline/graphql-php#8]
We need to think carefully about how we implement exception handling. There are three things to keep in mind:

* normally, if one field fails to resolve with an exception, the rest of the fields should still resolve and the query should just include `errors`
* this means exceptions get swallowed, so applications that report uncaught exceptions (technically these are caught, but only implicitly) need an easy way to access the underlying exceptions after the full query is resolved
* while developing you may not want GraphQL to swallow exceptions, instead you may want eventual exceptions to remain uncaught so they bubble up to the application's exception handler (which then usually renders it with a stack trace)

**Comment by crisu83** [comment]
@Jalle19 can you please write the description of this issue? Thank you in advance.

**Comment by Jalle19** [comment]
@crisu83 I added some notes

**Comment by crisu83** [comment]
@Jalle19 looks good.

**Comment by crisu83** [comment]
Here is a list of runtime exceptions that exist in the Java implementation:
http://graphql-java.readthedocs.io/en/v7/exceptions.html

**Comment by Jalle19** [comment]
Thanks, could make sense to try to follow those

**Comment by olivernybroe** [comment]
I think the cleanest way is to use `set_exception_handler` and then use `restore_exception_handler` afterwards.

**Comment by crisu83** [comment]
This was done in #288.
